#[Info]
site_name: DopplerXD Docs #网站名字
site_description: the notes record by DopplerXD
site_author: DopplerXD #作者名
site_url: https://DopplerXD.github.io/ #网站地址
copyright: Copyright &copy; 2024 DopplerXD # 左下角的版权声明

# Repository
repo_name: DopplerXD.github.io
repo_url: https://github.com/DopplerXD/DopplerXD.github.io

#[UI]
theme:
  name: material
  language: zh # 一些提示性的文字会变成中文
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - header.autohide #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.instant #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    # - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.tabs
    - navigation.prune
    - navigation.footer
    - navigation.tabs.sticky #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - content.code.copy
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 代码复制按钮
    - content.code.annotate # 代码块注释
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 日间模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 跟随系统
  favicon: assets/favicon.png
  icon:
    logo: material/library

#   icon:
#     repo: fontawesome/brands/github #右上角图标
#     logo: logo
# repo_name: DopplerXD.github.io # 右上角的名
# repo_url: https://github.com/DopplerXD/DopplerXD.github.io.git # 右上角点击跳转的链接

markdown_extensions:
  - admonition
  - abbr
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      title: On this page
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

extra:
  generator: true #删除页脚显示“使用 MkDocs 材料制造”
  social:
  #  - icon: fontawesome/brands/twitter
  #    link: https://twitter.com/
    - icon: fontawesome/brands/github
      link: https://github.com/DopplerXD/
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/32152704/
    - icon: material/email
      link: mailto:<1509209607@qq.com> #联系方式
    - icon: material/gmail
      link: mailto:<doppleryxc@gmail.com> #联系方式
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/DopplerXD/
    - icon: material/home
      link: https://www.dopplerxd.site/
      name: DopplerXD's Blog
  #

#  analytics:
#    provider: google
#    property: G-XXXXXXXXXX # Google Analytics ID
#    feedback:
#      title: 此页面有帮助吗？
#      ratings:
#        - icon: material/thumb-up-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            谢谢你的反馈！
#        - icon: material/thumb-down-outline
#          name: This page could be improved
#          data: 0
#          note: >-
#            Thanks for your feedback! Help us improve this page by
#            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
#
#  consent:
#    title: Cookie consent
#    description: >-
#      我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
#      如果你同意,你可以帮助我们让我们的网站更好

plugins:
  - search
  # - tags:
  #     tags_file: tag.md #标签
  - git-revision-date-localized:
      type: date
      enable_creation_date: true

# [Navigtion]
nav:
  - Home: index.md
  - 题解: 
    - 目录: Solution/index.md
    # - XCPC:
    - 2024_CCPC_Harbin_B: Solution/XCPC/24_CCPC_Harbin_B.md
    # - Codeforces: 
    # - Atcoder: 
    # - OJ: 
    # - GPLT: 
    - 2021总决赛: Solution/GPLT/2021_final.md
  - 代码模板: 
    - 目录: CodeModel/index.md
    - 基础/杂项: CodeModel/Basic_and_others.md
    - 图论: CodeModel/Graph_theory.md
    - 数据结构: CodeModel/Data_structure.md
    - 树: CodeModel/Tree.md
    - 线段树: CodeModel/Segment_tree.md
    - 字符串: CodeModel/String.md
    - 动态规划: CodeModel/Dynamic_programming.md
    - 数论: CodeModel/Number_theory.md
    - 组合数学: CodeModel/Combinatorics.md
    - 计算几何: CodeModel/Computational_geometry.md
    - 高精度: CodeModel/High_precision_calc.md
    - STL: CodeModel/STL.md
    - atcoder 封装: CodeModel/AtcoderModel.md
    - python: CodeModel/python.md
  - 专题总结:
    - 目录: Topic/index.md
    - 数据挖掘复习总结: Topic/DataMining.md
    - 地信复习总结: Topic/地信复习.md
  - 开发总结:
    - 目录: Develop/index.md
    - 前端: Develop/Frontend
    - 后端: Develop/Backend
    - 项目: Develop/Project
  - 找工作:
    - 目录: Job/index.md
    - 常见面试题:
      - Java: Job/Interview/FrequentQ/java.md
      - 计算机基础: Job/Interview/FrequentQ/computer-basis.md
      - 数据库: Job/Interview/FrequentQ/database.md
      - 系统设计: Job/Interview/FrequentQ/system-design.md
      - 高性能: Job/Interview/FrequentQ/high-performance.md
  - 使用经验: Skill/index.md
  - 资源平台: Resource/index.md
  - 杂项: Other/index.md
