authors:
  <author>:
    name: doppler
    description: CUGB, java
    avatar: https://cdn.acwing.com/media/user/profile/photo/450178_lg_963ea242b1.jpg
    slug: https://www.dopplerxd.top
    url: https://www.dopplerxd.site